name: va_bookats
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.3
  collection: ^1.18.0
  shared_preferences: ^2.5.5
  google_fonts: ^8.1.0
  carousel_slider: ^5.1.2
  # change_app_package_name: ^1.5.0
  url_launcher: ^6.3.2
  dio: ^5.9.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  google_maps_flutter: ^2.7.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  shimmer: ^3.0.0
  pusher_channels_flutter: ^2.6.0
  firebase_messaging: ^16.3.0
  firebase_core: ^4.10.0
  cached_network_image: ^3.4.1
  awesome_notifications: ^0.11.0
  file_picker: ^8.3.7
  record: ^6.2.1
  just_audio: ^0.10.5
  path_provider: ^2.1.6
  video_player: ^2.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/
