part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const LOGIN = _Paths.LOGIN;
  static const ALL_BOOKING = _Paths.ALL_BOOKING;
  static const BOOKING_DETAILS = _Paths.BOOKING_DETAILS;
  static const PAYMENTS = _Paths.PAYMENTS;
  static const CREATE_BOOKING = _Paths.CREATE_BOOKING;
  static const SERVICES = _Paths.SERVICES;
  static const ADD_SERVICE = _Paths.ADD_SERVICE;
  static const SERVICE_CATEGORIES = _Paths.SERVICE_CATEGORIES;
  static const ADD_SERVICE_CATEGORY = _Paths.ADD_SERVICE_CATEGORY;
  static const PACKAGES = _Paths.PACKAGES;
  static const ADD_PACKAGE = _Paths.ADD_PACKAGE;
  static const CUSTOMERS = _Paths.CUSTOMERS;
  static const ADD_CUSTOMER = _Paths.ADD_CUSTOMER;
  static const REVENUE_REPORT = _Paths.REVENUE_REPORT;
  static const BOTTOMNAV = _Paths.BOTTOMNAV;
  static const ONBOARD = _Paths.ONBOARD;
  static const SPLASH = _Paths.SPLASH;
  static const PROFILE = _Paths.PROFILE;
  static const APP_DRAWER = _Paths.APP_DRAWER;
  static const PERSONAL_INFO = _Paths.PERSONAL_INFO;
  static const UPDATE_PASSWORD = _Paths.UPDATE_PASSWORD;
  static const PAYMENT_DETAILS = _Paths.PAYMENT_DETAILS;
  static const MEDIA_LIBRARY = _Paths.MEDIA_LIBRARY;
  static const BRANCH_COMPARISON = _Paths.BRANCH_COMPARISON;
  static const BRANCH_COMPARISON_REPORT = _Paths.BRANCH_COMPARISON_REPORT;
  static const BRANCH_COMPARISON_REPORT_DETAILS = _Paths.BRANCH_COMPARISON_REPORT_DETAILS;
  static const SERVICE_REVENUE_REPORT = _Paths.SERVICE_REVENUE_REPORT;
  static const SERVICE_REVENUE_DETAILS = _Paths.SERVICE_REVENUE_DETAILS;
  static const PRODUCT_REVENUE_REPORT = _Paths.PRODUCT_REVENUE_REPORT;
  static const PRODUCT_REVENUE_DETAILS = _Paths.PRODUCT_REVENUE_DETAILS;
  static const PACKAGE_REVENUE_REPORT = _Paths.PACKAGE_REVENUE_REPORT;
  static const PACKAGE_REVENUE_DETAILS = _Paths.PACKAGE_REVENUE_DETAILS;
  static const COMMISSIONS_REPORT = _Paths.COMMISSIONS_REPORT;
  static const COMMISSIONS_DETAIL = _Paths.COMMISSIONS_DETAIL;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const LOGIN = '/login';
  static const ALL_BOOKING = '/all-booking';
  static const BOOKING_DETAILS = '/booking-details';
  static const PAYMENTS = '/payments';
  static const CREATE_BOOKING = '/create-booking';
  static const SERVICES = '/services';
  static const ADD_SERVICE = '/add-service';
  static const SERVICE_CATEGORIES = '/service-categories';
  static const ADD_SERVICE_CATEGORY = '/add-service-category';
  static const PACKAGES = '/packages';
  static const ADD_PACKAGE = '/add-package';
  static const CUSTOMERS = '/customers';
  static const ADD_CUSTOMER = '/add-customer';
  static const REVENUE_REPORT = '/revenue-report';
  static const BOTTOMNAV = '/bottomnav';
  static const ONBOARD = '/onboard';
  static const SPLASH = '/splash';
  static const PROFILE = '/profile';
  static const APP_DRAWER = '/app-drawer';
  static const PERSONAL_INFO = '/personal-info';
  static const UPDATE_PASSWORD = '/update-password';
  static const PAYMENT_DETAILS = '/payment-details';
  static const MEDIA_LIBRARY = '/media-library';
  static const BRANCH_COMPARISON = '/branch-comparison';
  static const BRANCH_COMPARISON_REPORT = '/branch-comparison-report';
  static const BRANCH_COMPARISON_REPORT_DETAILS = '/branch-comparison-report-details';
  static const SERVICE_REVENUE_REPORT = '/service-revenue-report';
  static const SERVICE_REVENUE_DETAILS = '/service-revenue-details';
  static const PRODUCT_REVENUE_REPORT = '/product-revenue-report';
  static const PRODUCT_REVENUE_DETAILS = '/product-revenue-details';
  static const PACKAGE_REVENUE_REPORT = '/package-revenue-report';
  static const PACKAGE_REVENUE_DETAILS = '/package-revenue-details';
  static const COMMISSIONS_REPORT = '/commissions-report';
  static const COMMISSIONS_DETAIL = '/commissions-detail';
}
